import * as THREE from 'three';
const canvas=document.querySelector('#ocean'),scene=new THREE.Scene();
scene.fog=new THREE.FogExp2(0x03151d,.027);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
camera.position.set(0,0,14);scene.add(new THREE.AmbientLight(0x4bc4db,1.5));const sun=new THREE.DirectionalLight(0xd9fcff,3);sun.position.set(5,6,7);scene.add(sun);
const world=new THREE.Group();world.position.x=2.6;scene.add(world);
const state={depth:.78,current:.35,purity:.78,jellies:.35,fish:.6,large:.55,trash:.2,life:.78,wave:.3,speed:.45,light:.7,sound:.35,chill:.7,rotX:.5,rotY:.5,zoom:.55,playing:true,deep:false};
const oceanMat=new THREE.MeshPhysicalMaterial({color:0x08758e,transparent:true,opacity:.48,roughness:.12,metalness:.05,transmission:.35,thickness:1.5,clearcoat:1});
const ocean=new THREE.Mesh(new THREE.SphereGeometry(3.12,64,64),oceanMat);world.add(ocean);
const shell=new THREE.Mesh(new THREE.SphereGeometry(3.28,64,64),new THREE.MeshPhysicalMaterial({color:0x9cecff,transparent:true,opacity:.09,roughness:0,transmission:.95,thickness:.2,side:THREE.DoubleSide}));world.add(shell);
const glow=new THREE.Mesh(new THREE.SphereGeometry(3.42,32,32),new THREE.MeshBasicMaterial({color:0x1bcce7,transparent:true,opacity:.035,side:THREE.BackSide}));world.add(glow);
const particles=new THREE.BufferGeometry(),pts=[];for(let i=0;i<900;i++){const r=3.5+Math.random()*9,a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1);pts.push(r*Math.sin(b)*Math.cos(a),r*Math.sin(b)*Math.sin(a),r*Math.cos(b))}particles.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));scene.add(new THREE.Points(particles,new THREE.PointsMaterial({color:0x74dceb,size:.018,transparent:true,opacity:.4})));
const creatures={fish:[],jelly:[],large:[],trash:[]};
function mat(color,opacity=1){return new THREE.MeshStandardMaterial({color,transparent:opacity<1,opacity,roughness:.5})}
function randomPos(r=2.5){const v=new THREE.Vector3().randomDirection().multiplyScalar(Math.cbrt(Math.random())*r);return v}
function addFish(i){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.SphereGeometry(.08,.12?8:8,6),mat(i%4?0x8adfe9:0xffc979));body.scale.set(1.8,.7,.65);g.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.08,.18,3),body.material);tail.rotation.z=-Math.PI/2;tail.position.x=-.18;g.add(tail);g.position.copy(randomPos());g.userData={phase:Math.random()*9,s:.2+Math.random()*.25};world.add(g);creatures.fish.push(g)}
function addJelly(){const g=new THREE.Group(),head=new THREE.Mesh(new THREE.SphereGeometry(.14,12,8,0,Math.PI*2,0,Math.PI/2),new THREE.MeshBasicMaterial({color:0xa7f4ff,transparent:true,opacity:.65}));g.add(head);for(let i=0;i<3;i++){const t=new THREE.Mesh(new THREE.CylinderGeometry(.008,.004,.28,4),head.material);t.position.set((i-1)*.05,-.14,0);g.add(t)}g.position.copy(randomPos(2.6));g.userData={phase:Math.random()*9};world.add(g);creatures.jelly.push(g)}
function addLarge(type='whale'){const g=new THREE.Group(),color=type==='turtle'?0x5bb89a:0x5d9dac,body=new THREE.Mesh(new THREE.SphereGeometry(.3,16,10),mat(color));body.scale.set(type==='turtle'?1.2:3,type==='turtle'?.35:.65,1);g.add(body);const tail=new THREE.Mesh(new THREE.ConeGeometry(.22,.38,3),body.material);tail.rotation.z=-Math.PI/2;tail.position.x=-.85;g.add(tail);g.position.copy(randomPos(2));g.scale.setScalar(type==='dolphin'?.55:type==='turtle'?.65:1);g.userData={phase:Math.random()*9,type};world.add(g);creatures.large.push(g);return g}
function addTrash(){const mesh=new THREE.Mesh(Math.random()>.5?new THREE.BoxGeometry(.1,.18,.06):new THREE.CylinderGeometry(.05,.05,.2,7),mat(Math.random()>.5?0xeae3c4:0xd65f66,.85));mesh.position.copy(randomPos());mesh.rotation.set(Math.random()*3,Math.random()*3,0);mesh.userData={phase:Math.random()*9};world.add(mesh);creatures.trash.push(mesh)}
for(let i=0;i<80;i++)addFish(i);for(let i=0;i<36;i++)addJelly();for(let i=0;i<3;i++)addLarge(i===1?'dolphin':i===2?'turtle':'whale');for(let i=0;i<45;i++)addTrash();
const defs=[['depth','海水深度'],['current','洋流強度'],['purity','海洋純淨度'],['jellies','水母數量'],['fish','魚群數量'],['large','大型生物'],['trash','海洋垃圾'],['life','生命力'],['rotX','球體 X 軸'],['rotY','球體 Y 軸'],['zoom','視角距離'],['wave','海浪幅度'],['speed','水流速度'],['light','光線'],['sound','環境音'],['chill','Chill 程度']];
const controls=document.querySelector('#controls');
defs.forEach(([key,name],i)=>{const d=document.createElement('div');d.className='control';d.innerHTML='<label><span>'+name+'</span><output>'+Math.round(state[key]*127)+'</output></label><input type="range" min="0" max="127" value="'+Math.round(state[key]*127)+'" data-key="'+key+'"><small>'+(i<8?'SLIDER '+(i+1):'KNOB '+(i-7))+'</small>';controls.append(d)});
function setValue(key,val,ui=true){state[key]=THREE.MathUtils.clamp(val,0,1);if(ui){const e=document.querySelector('[data-key="'+key+'"]');if(e){e.value=Math.round(val*127);e.parentElement.querySelector('output').textContent=Math.round(val*127)}}updateWorld()}
function updateWorld(){ocean.scale.y=.55+state.depth*.45;oceanMat.opacity=.2+state.depth*.42;oceanMat.color.setHSL(.52+state.purity*.015,.72,.12+state.purity*.16);creatures.fish.forEach((o,i)=>o.visible=i<state.fish*creatures.fish.length);creatures.jelly.forEach((o,i)=>o.visible=i<state.jellies*creatures.jelly.length);creatures.large.forEach((o,i)=>o.visible=i<Math.ceil(state.large*creatures.large.length));creatures.trash.forEach((o,i)=>o.visible=i<state.trash*creatures.trash.length);sun.intensity=.25+state.light*3.5;camera.position.z=18-state.zoom*7;const health=Math.round(100*(state.purity*.34+(1-state.trash)*.28+state.life*.26+(1-Math.abs(state.current-.4))*.12));document.querySelector('#healthNumber').textContent=health+'%';document.querySelector('#healthBar').style.width=health+'%';document.querySelector('#healthText').textContent=health>75?'穩定':health>45?'失衡':'危急'}
controls.addEventListener('input',e=>{if(e.target.matches('input'))setValue(e.target.dataset.key,+e.target.value/127)});
let toastTimer;function toast(icon,msg){const el=document.querySelector('#toast');el.querySelector('span').textContent=icon;el.querySelector('p').textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function event(name){const burst=(type,n)=>{for(let i=0;i<n;i++){const o=addLarge(type);o.scale.setScalar(.01);setTimeout(()=>o.scale.setScalar(type==='dolphin'?.55:.85),i*100)}};({whale:()=>{burst('whale',1);toast('🐋','一隻鯨魚從星球深處緩緩游過')},dolphin:()=>{burst('dolphin',5);toast('🐬','海豚群穿越了洋流')},jelly:()=>{setValue('jellies',1);toast('🪼','發光水母正在大量浮起')},turtle:()=>{burst('turtle',1);toast('🐢','海龜回到了乾淨的棲地')},pollution:()=>{setValue('trash',.9);setValue('purity',.25);toast('🗑️','污染升高，海洋生命正在受影響')},current:()=>{setValue('current',1);toast('🌊','強烈洋流席捲整顆星球')},deep:()=>{state.deep=!state.deep;setValue('light',state.deep?.08:.7);toast('🌑',state.deep?'進入深海，只剩生命微光':'返回明亮海面')},clean:()=>{setValue('trash',0);setValue('purity',1);setValue('life',1);toast('✨','海洋完成淨化，生命正在復甦')},play:()=>{state.playing=true;toast('▶','星球開始呼吸')},stop:()=>{state.playing=false;toast('■','海洋慢慢靜止')},record:()=>{setValue('trash',1);setValue('purity',.05);setValue('life',.15);toast('●','人類污染入侵，生態進入危急狀態')}}[name]||(()=>{}))()}
document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>event(b.dataset.event));
document.querySelector('#enterBtn').onclick=()=>document.querySelector('#panel').classList.add('open');document.querySelector('#closePanel').onclick=()=>document.querySelector('#panel').classList.remove('open');document.querySelector('#storyBtn').onclick=()=>document.querySelector('#concept').classList.add('open');document.querySelector('#closeStory').onclick=()=>document.querySelector('#concept').classList.remove('open');
const midiBtn=document.querySelector('#midiBtn'),sliderCC=[0,1,2,3,4,5,6,7],knobCC=[16,17,18,19,20,21,22,23],keys=defs.map(x=>x[0]),buttonMap={32:'whale',33:'dolphin',34:'jelly',35:'turtle',48:'pollution',49:'current',50:'deep',51:'clean',41:'play',42:'stop',45:'record'};
midiBtn.onclick=async()=>{if(!navigator.requestMIDIAccess){toast('⚠️','此瀏覽器不支援 Web MIDI，請使用 Chrome 或 Edge');return}try{const access=await navigator.requestMIDIAccess();const bind=()=>{let n=0;access.inputs.forEach(input=>{input.onmidimessage=onMIDI;n++});midiBtn.classList.toggle('connected',n>0);midiBtn.querySelector('span').textContent=n?'nanoKONTROL2 已連接':'等待 MIDI 裝置';toast(n?'✅':'⚠️',n?'生命控制台已連接':'找不到 MIDI 輸入裝置')};bind();access.onstatechange=bind}catch(e){toast('⚠️','MIDI 權限未開啟')}};
function onMIDI(e){const [status,cc,value]=e.data;if((status&0xf0)!==0xb0)return;let idx=sliderCC.indexOf(cc);if(idx<0){const k=knobCC.indexOf(cc);if(k>=0)idx=k+8}if(idx>=0)setValue(keys[idx],value/127);if(value>0&&buttonMap[cc])event(buttonMap[cc])}
addEventListener('keydown',e=>{const map={q:'whale',w:'dolphin',e:'jelly',r:'turtle',a:'pollution',s:'current',d:'deep',f:'clean',' ':'play'};if(map[e.key.toLowerCase()])event(map[e.key.toLowerCase()])});
let t=0;function animate(){requestAnimationFrame(animate);const dt=.008*(.3+state.speed)*(1.4-state.chill);if(state.playing)t+=dt;world.rotation.y+=(state.rotX-.5)*.007+state.current*.001;world.rotation.x=(state.rotY-.5)*.65;const swim=(arr,mult=1)=>arr.forEach((o,i)=>{if(!o.visible)return;const p=o.userData.phase||0;o.position.x+=dt*(o.userData.s||.08)*mult;o.position.y+=Math.sin(t*3+p)*.0015;if(o.position.x>2.8)o.position.x=-2.8});swim(creatures.fish,2);swim(creatures.large,.7);creatures.jelly.forEach(o=>{o.position.y+=dt*.08;if(o.position.y>2.8)o.position.y=-2.8;o.scale.setScalar(1+Math.sin(t*4+o.userData.phase)*.08)});creatures.trash.forEach(o=>{o.rotation.y+=dt;o.position.y+=Math.sin(t+o.userData.phase)*.0005});shell.scale.setScalar(1+Math.sin(t*2)*state.wave*.006);particles.rotation.y=t*.02;renderer.render(scene,camera)}updateWorld();animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);world.position.x=innerWidth<760?1.1:2.6});if(innerWidth<760)world.position.x=1.1;